# netlify.toml
[build]
  command = "npm run build"
  publish = ".next"            # for server-rendered Next on Netlify

[build.environment]
  NODE_VERSION = "22.18.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"
