[build]
  base = "supabase-scheduler-10/reference"
  publish = "."
  command = "echo 'No build needed for static HTML'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/original-app.html"
  status = 200
  force = false

# Optional: Set custom headers for your HTML file
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
