[build]
  base = "supabase-scheduler-10"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.18.0"
  NEXT_PUBLIC_SITE_URL = "https://msweeklyboard.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Add this redirect rule to handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
